
import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'it' | 'en' | 'es';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>(() => {
    const saved = localStorage.getItem('tralis_language');
    return (saved as Language) || 'it';
  });

  useEffect(() => {
    localStorage.setItem('tralis_language', language);
  }, [language]);

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

const translations = {
  it: {
    // Navigation
    'nav.product': 'PRODOTTO',
    'nav.solutions': 'SOLUZIONI', 
    'nav.why': 'PERCHÉ TRALIS AI?',
    'nav.resources': 'RISORSE',
    'nav.pricing': 'PREZZI',
    'nav.login': 'Accedi',
    'nav.signup': 'Registrati Gratis',
    'nav.contact': 'Contattaci',
    'nav.glossary': 'Glossario',
    
    // Sidebar
    'sidebar.dashboard': 'Dashboard',
    'sidebar.analytics': 'Analytics',
    'sidebar.reports': 'Report',
    'sidebar.data-import': 'Importa Dati',
    'sidebar.ai-solution': 'Soluzione AI',
    'sidebar.lending': 'Finanziamenti',
    'sidebar.calendar': 'Calendario',
    'sidebar.packages': 'Pacchetti',
    
    // Header
    'header.profile': 'Profilo',
    'header.settings': 'Impostazioni',
    'header.logout': 'Esci',
    'header.plan': 'Piano',
    
    // Auth Modal
    'auth.welcome': 'Bentornato',
    'auth.credentials': 'Inserisci le tue credenziali per accedere alla tua dashboard Tralis AI',
    'auth.create': 'Crea Account',
    'auth.join': 'Unisciti a Tralis AI e sblocca il tuo potenziale finanziario',
    'auth.email': 'Email',
    'auth.password': 'Password',
    'auth.firstName': 'Nome',
    'auth.lastName': 'Cognome',
    'auth.company': 'Azienda',
    'auth.login': 'Accedi',
    'auth.signup': 'Crea Account',
    'auth.logging': 'Accesso in corso...',
    'auth.creating': 'Creazione account...',
    'auth.terms': 'Continuando, accetti i Termini di Servizio e la Privacy Policy di Tralis AI',
    
    // Dashboard
    'dashboard.title': 'Dashboard Finanziaria',
    'dashboard.subtitle': 'Panoramica completa delle tue performance finanziarie',
    'dashboard.welcome': 'Benvenuto nella tua dashboard finanziaria',
    'dashboard.overview': 'Panoramica',
    'dashboard.revenue': 'Ricavi',
    'dashboard.expenses': 'Spese',
    'dashboard.profit': 'Profitto',
    'dashboard.cashflow': 'Flusso di Cassa',
    'dashboard.month': 'Questo Mese',
    'dashboard.growth': 'Crescita',
    'dashboard.vs-last': 'vs mese scorso',
    'dashboard.financial-summary': 'Riepilogo Finanziario',
    'dashboard.recent-transactions': 'Transazioni Recenti',
    'dashboard.view-all': 'Visualizza Tutto',
    'dashboard.cash-flow-trend': 'Trend del Flusso di Cassa',
    'dashboard.revenue-breakdown': 'Suddivisione Ricavi',
    'dashboard.alerts': 'Avvisi',
    'dashboard.no-alerts': 'Nessun avviso al momento',
    'dashboard.quick-actions': 'Azioni Rapide',
    'dashboard.generate-report': 'Genera Report',
    'dashboard.schedule-meeting': 'Programma Riunione',
    'dashboard.ai-insights': 'Insights AI',
    
    // Analytics
    'analytics.title': 'Analytics Avanzate',
    'analytics.subtitle': 'Analisi approfondite delle tue performance finanziarie',
    'analytics.revenue-trend': 'Trend Ricavi',
    'analytics.expense-breakdown': 'Ripartizione Spese',
    'analytics.profit-margin': 'Margine di Profitto',
    'analytics.kpi': 'Indicatori Chiave',
    'analytics.forecast': 'Previsioni',
    'analytics.insights': 'Insights',
    'analytics.performance': 'Performance',
    'analytics.comparison': 'Confronto',
    'analytics.financial-ratios': 'Ratios Finanziari',
    'analytics.liquidity': 'Liquidità',
    'analytics.profitability': 'Redditività',
    'analytics.efficiency': 'Efficienza',
    'analytics.leverage': 'Leva Finanziaria',
    'analytics.market-analysis': 'Analisi di Mercato',
    'analytics.competitive-analysis': 'Analisi Competitiva',
    'analytics.scenario-analysis': 'Analisi Scenari',
    'analytics.risk-assessment': 'Valutazione Rischi',
    
    // Reports
    'reports.title': 'Report Finanziari',
    'reports.subtitle': 'Genera e visualizza report dettagliati',
    'reports.monthly': 'Report Mensile',
    'reports.quarterly': 'Report Trimestrale',
    'reports.annual': 'Report Annuale',
    'reports.custom': 'Report Personalizzato',
    'reports.generate': 'Genera Report',
    'reports.download': 'Scarica',
    'reports.export': 'Esporta',
    'reports.financial-statements': 'Bilanci',
    'reports.cash-flow-statement': 'Rendiconto Flussi di Cassa',
    'reports.income-statement': 'Conto Economico',
    'reports.balance-sheet': 'Stato Patrimoniale',
    'reports.investor-reports': 'Report per Investitori',
    'reports.executive-summary': 'Riassunto Esecutivo',
    'reports.detailed-analysis': 'Analisi Dettagliata',
    'reports.templates': 'Modelli',
    'reports.scheduled': 'Report Programmati',
    'reports.history': 'Storico Report',
    
    // AI Solution
    'ai.title': 'Soluzione AI',
    'ai.subtitle': 'Assistente AI per analisi finanziarie avanzate',
    'ai.assistant': 'Assistente AI Tralis AI',
    'ai.analysis': 'Analisi automatica e comandi intelligenti per la tua azienda',
    'ai.ask': 'Chiedi al tuo assistente AI',
    'ai.send': 'Invia',
    'ai.suggestions': 'Suggerimenti',
    'ai.insights': 'Insights AI',
    'ai.chat': 'Chat AI',
    'ai.scenario-analysis': 'Analisi Scenari',
    'ai.financial-modeling': 'Modellazione Finanziaria',
    'ai.predictive-analytics': 'Analytics Predittivi',
    'ai.recommendations': 'Raccomandazioni',
    'ai.automated-reports': 'Report Automatizzati',
    'ai.intelligent-alerts': 'Avvisi Intelligenti',
    'ai.conversation-history': 'Cronologia Conversazioni',
    'ai.save-analysis': 'Salva Analisi',
    
    // Lending
    'lending.title': 'Soluzioni di Finanziamento',
    'lending.subtitle': 'Trova le migliori opzioni di finanziamento per la tua azienda',
    'lending.options': 'Opzioni Disponibili',
    'lending.apply': 'Richiedi Finanziamento',
    'lending.calculator': 'Calcolatore Prestiti',
    'lending.eligibility': 'Verifica Idoneità',
    'lending.loan-types': 'Tipi di Prestiti',
    'lending.business-loan': 'Prestito Aziendale',
    'lending.line-of-credit': 'Linea di Credito',
    'lending.equipment-financing': 'Finanziamento Attrezzature',
    'lending.invoice-factoring': 'Factoring Fatture',
    'lending.requirements': 'Requisiti',
    'lending.documentation': 'Documentazione',
    'lending.application-status': 'Stato Richiesta',
    'lending.interest-rates': 'Tassi di Interesse',
    'lending.terms': 'Condizioni',
    'lending.pre-approval': 'Pre-approvazione',
    
    // Calendar
    'calendar.title': 'Calendario Finanziario',
    'calendar.subtitle': 'Gestisci scadenze e appuntamenti importanti',
    'calendar.events': 'Eventi',
    'calendar.deadlines': 'Scadenze',
    'calendar.meetings': 'Riunioni',
    'calendar.add': 'Aggiungi Evento',
    'calendar.today': 'Oggi',
    'calendar.week': 'Settimana',
    'calendar.month': 'Mese',
    'calendar.year': 'Anno',
    'calendar.upcoming': 'Prossimi Eventi',
    'calendar.overdue': 'Scaduti',
    'calendar.reminders': 'Promemoria',
    'calendar.notifications': 'Notifiche',
    'calendar.recurring': 'Ricorrenti',
    'calendar.sync': 'Sincronizza',
    'calendar.export': 'Esporta',
    'calendar.import': 'Importa',
    
    // Packages
    'packages.title': 'Pacchetti e Piani',
    'packages.subtitle': 'Scegli il piano perfetto per le tue esigenze',
    'packages.current': 'Piano Attuale',
    'packages.upgrade': 'Aggiorna',
    'packages.features': 'Funzionalità',
    'packages.contact': 'Contatta il Team',
    'packages.free': 'Gratuito',
    'packages.basic': 'Basic',
    'packages.professional': 'Professional',
    'packages.enterprise': 'Enterprise',
    'packages.monthly': 'Mensile',
    'packages.yearly': 'Annuale',
    'packages.save': 'Risparmia',
    'packages.most-popular': 'Più Popolare',
    'packages.unlimited': 'Illimitato',
    'packages.support': 'Supporto',
    'packages.billing': 'Fatturazione',
    'packages.cancel-anytime': 'Cancella in qualsiasi momento',
    
    // Data Import
    'import.title': 'Importa Dati',
    'import.subtitle': 'Carica i tuoi dati finanziari',
    'import.upload': 'Carica File',
    'import.excel': 'File Excel',
    'import.csv': 'File CSV',
    'import.template': 'Scarica Template',
    'import.process': 'Elabora',
    'import.supported-formats': 'Formati Supportati',
    'import.drag-drop': 'Trascina e rilascia i file qui',
    'import.or': 'oppure',
    'import.browse': 'Sfoglia File',
    'import.max-size': 'Dimensione massima',
    'import.preview': 'Anteprima',
    'import.mapping': 'Mappatura Campi',
    'import.validation': 'Validazione',
    'import.import-progress': 'Progresso Importazione',
    'import.success': 'Importazione completata con successo',
    'import.error': 'Errore durante l\'importazione',
    'import.history': 'Cronologia Importazioni',
    
    // User Profile
    'profile.title': 'Profilo Utente',
    'profile.personal': 'Informazioni Personali',
    'profile.company': 'Informazioni Azienda',
    'profile.security': 'Sicurezza',
    'profile.save': 'Salva Modifiche',
    'profile.edit': 'Modifica',
    'profile.change-password': 'Cambia Password',
    'profile.current-password': 'Password Attuale',
    'profile.new-password': 'Nuova Password',
    'profile.confirm-password': 'Conferma Password',
    'profile.two-factor': 'Autenticazione a Due Fattori',
    'profile.notifications': 'Notifiche',
    'profile.preferences': 'Preferenze',
    'profile.timezone': 'Fuso Orario',
    'profile.language': 'Lingua',
    'profile.currency': 'Valuta',
    'profile.delete-account': 'Elimina Account',
    
    // Homepage Hero
    'hero.badge': 'Innovazione Globale',
    'hero.title': 'Libera il Potenziale',
    'hero.title.highlight': 'Finanziario',
    'hero.title.end': 'della Tua Startup',
    'hero.subtitle': 'Diamo potere alle startup e PMI per competere con aziende più grandi attraverso analisi finanziarie all\'avanguardia e consigli powered by AI. Trasforma la tua gestione finanziaria e sblocca il potenziale del tuo business.',
    'hero.cta.primary': 'Inizia Prova Gratuita',
    'hero.cta.secondary': 'Accedi al Tuo Account',
    
    // Video Section
    'video.title': 'Scopri Tralis AI in Azione',
    'video.subtitle': 'Guarda come Tralis AI trasforma la gestione finanziaria della tua azienda con un tour completo della piattaforma.',
    'video.tutorial.title': 'Tutorial Completo Tralis AI',
    'video.tutorial.duration': 'Durata: 8 minuti',
    'video.tutorial.cta': 'Guarda il Video',
    'video.card1.title': 'Dashboard Finanziaria',
    'video.card1.desc': 'Visualizza KPI e metriche in tempo reale',
    'video.card2.title': 'AI Analytics',
    'video.card2.desc': 'Insights predittivi e raccomandazioni',
    'video.card3.title': 'Report Avanzati',
    'video.card3.desc': 'Documenti pronti per investitori',
    
    // Features
    'features.title': 'Tutto Quello che Ti Serve per Padroneggiare le Tue Finanze',
    'features.subtitle': 'La nostra piattaforma completa fornisce tutti gli strumenti e insights necessari per prendere decisioni finanziarie informate e guidare la crescita.',
    'features.dashboard.title': 'Dashboard in Tempo Reale',
    'features.dashboard.desc': 'Monitora la salute finanziaria della tua azienda con visualizzazioni intuitive e indicatori chiave di performance.',
    'features.ai.title': 'Insights Powered by AI',
    'features.ai.desc': 'Ricevi raccomandazioni personalizzate e analisi predittive su misura per la tua attività.',
    'features.security.title': 'Sicuro e Conforme',
    'features.security.desc': 'Sicurezza di livello enterprise con piena conformità alle normative internazionali.',
    'features.funding.title': 'Preparazione Finanziamenti',
    'features.funding.desc': 'Preparati per gli investimenti con report finanziari completi e proiezioni.',
    
    // Testimonials
    'testimonials.title': 'Scelto da Aziende in Crescita',
    'testimonials.quote1': 'Tralis AI ha rivoluzionato il modo in cui gestiamo le nostre finanze. Gli insights AI sono incredibilmente accurati.',
    'testimonials.quote2': 'Finalmente, una piattaforma finanziaria costruita specificamente per le startup. Le dashboard sono incredibili!',
    
    // CTA Section
    'cta.title': 'Pronto a Trasformare la Tua Gestione Finanziaria?',
    'cta.subtitle': 'Unisciti a centinaia di startup che già usano Tralis AI per guidare la crescita e prendere decisioni migliori.',
    'cta.button': 'Inizia Oggi',
    
    // Why Tralis AI Section
    'why.title': 'Perché Scegliere Tralis AI?',
    'why.subtitle': 'La piattaforma di intelligenza finanziaria più avanzata per startup e PMI',
    'why.ai-powered': 'Powered by AI',
    'why.ai-powered.desc': 'Algoritmi di machine learning avanzati per analisi predittiva e insights automatici',
    'why.real-time': 'Dati in Tempo Reale',
    'why.real-time.desc': 'Monitora le performance della tua azienda con aggiornamenti istantanei e dashboard live',
    'why.compliance': 'Conformità Totale',
    'why.compliance.desc': 'Rispetta tutte le normative internazionali con report automatizzati e audit trail',
    'why.scalable': 'Scalabile',
    'why.scalable.desc': 'Cresce con la tua azienda, da startup a enterprise, con funzionalità modulari',
    'why.support': 'Supporto 24/7',
    'why.support.desc': 'Team di esperti disponibili sempre per supportare la tua crescita finanziaria',
    'why.integration': 'Integrazione Facile',
    'why.integration.desc': 'Connetti tutti i tuoi sistemi esistenti con API moderne e sicure',
    
    // Language Selection
    'language.select': 'Seleziona Lingua',
    'language.italian': 'Italiano',
    'language.english': 'English',
    'language.spanish': 'Español',
    
    // Common
    'common.loading': 'Caricamento...',
    'common.error': 'Errore',
    'common.success': 'Successo',
    'common.cancel': 'Annulla',
    'common.confirm': 'Conferma',
    'common.delete': 'Elimina',
    'common.edit': 'Modifica',
    'common.save': 'Salva',
    'common.back': 'Indietro',
    'common.next': 'Avanti',
    'common.previous': 'Precedente',
    'common.close': 'Chiudi',
    'common.search': 'Cerca',
    'common.filter': 'Filtra',
    'common.sort': 'Ordina',
    'common.refresh': 'Aggiorna',
    'common.settings': 'Impostazioni',
    'common.help': 'Aiuto',
    'common.documentation': 'Documentazione',
    'common.contact': 'Contatto',
    'common.support': 'Supporto',
  },
  en: {
    // Navigation
    'nav.product': 'PRODUCT',
    'nav.solutions': 'SOLUTIONS',
    'nav.why': 'WHY TRALIS AI?',
    'nav.resources': 'RESOURCES',
    'nav.pricing': 'PRICING',
    'nav.login': 'Login',
    'nav.signup': 'Sign Up Free',
    'nav.contact': 'Contact Us',
    'nav.glossary': 'Glossary',
    
    // Sidebar
    'sidebar.dashboard': 'Dashboard',
    'sidebar.analytics': 'Analytics',
    'sidebar.reports': 'Reports',
    'sidebar.data-import': 'Data Import',
    'sidebar.ai-solution': 'AI Solution',
    'sidebar.lending': 'Lending',
    'sidebar.calendar': 'Calendar',
    'sidebar.packages': 'Packages',
    
    // Header
    'header.profile': 'Profile',
    'header.settings': 'Settings',
    'header.logout': 'Logout',
    'header.plan': 'Plan',
    
    // Auth Modal
    'auth.welcome': 'Welcome Back',
    'auth.credentials': 'Enter your credentials to access your Tralis AI dashboard',
    'auth.create': 'Create Account',
    'auth.join': 'Join Tralis AI and unlock your financial potential',
    'auth.email': 'Email',
    'auth.password': 'Password',
    'auth.firstName': 'First Name',
    'auth.lastName': 'Last Name',
    'auth.company': 'Company',
    'auth.login': 'Login',
    'auth.signup': 'Create Account',
    'auth.logging': 'Logging in...',
    'auth.creating': 'Creating account...',
    'auth.terms': 'By continuing, you agree to Tralis AI\'s Terms of Service and Privacy Policy',
    
    // Dashboard
    'dashboard.title': 'Financial Dashboard',
    'dashboard.subtitle': 'Complete overview of your financial performance',
    'dashboard.welcome': 'Welcome to your financial dashboard',
    'dashboard.overview': 'Overview',
    'dashboard.revenue': 'Revenue',
    'dashboard.expenses': 'Expenses',
    'dashboard.profit': 'Profit',
    'dashboard.cashflow': 'Cash Flow',
    'dashboard.month': 'This Month',
    'dashboard.growth': 'Growth',
    'dashboard.vs-last': 'vs last month',
    'dashboard.financial-summary': 'Financial Summary',
    'dashboard.recent-transactions': 'Recent Transactions',
    'dashboard.view-all': 'View All',
    'dashboard.cash-flow-trend': 'Cash Flow Trend',
    'dashboard.revenue-breakdown': 'Revenue Breakdown',
    'dashboard.alerts': 'Alerts',
    'dashboard.no-alerts': 'No alerts at the moment',
    'dashboard.quick-actions': 'Quick Actions',
    'dashboard.generate-report': 'Generate Report',
    'dashboard.schedule-meeting': 'Schedule Meeting',
    'dashboard.ai-insights': 'AI Insights',
    
    // Analytics
    'analytics.title': 'Advanced Analytics',
    'analytics.subtitle': 'Deep insights into your financial performance',
    'analytics.revenue-trend': 'Revenue Trend',
    'analytics.expense-breakdown': 'Expense Breakdown',
    'analytics.profit-margin': 'Profit Margin',
    'analytics.kpi': 'Key Indicators',
    'analytics.forecast': 'Forecast',
    'analytics.insights': 'Insights',
    'analytics.performance': 'Performance',
    'analytics.comparison': 'Comparison',
    'analytics.financial-ratios': 'Financial Ratios',
    'analytics.liquidity': 'Liquidity',
    'analytics.profitability': 'Profitability',
    'analytics.efficiency': 'Efficiency',
    'analytics.leverage': 'Leverage',
    'analytics.market-analysis': 'Market Analysis',
    'analytics.competitive-analysis': 'Competitive Analysis',
    'analytics.scenario-analysis': 'Scenario Analysis',
    'analytics.risk-assessment': 'Risk Assessment',
    
    // Reports
    'reports.title': 'Financial Reports',
    'reports.subtitle': 'Generate and view detailed reports',
    'reports.monthly': 'Monthly Report',
    'reports.quarterly': 'Quarterly Report',
    'reports.annual': 'Annual Report',
    'reports.custom': 'Custom Report',
    'reports.generate': 'Generate Report',
    'reports.download': 'Download',
    'reports.export': 'Export',
    'reports.financial-statements': 'Financial Statements',
    'reports.cash-flow-statement': 'Cash Flow Statement',
    'reports.income-statement': 'Income Statement',
    'reports.balance-sheet': 'Balance Sheet',
    'reports.investor-reports': 'Investor Reports',
    'reports.executive-summary': 'Executive Summary',
    'reports.detailed-analysis': 'Detailed Analysis',
    'reports.templates': 'Templates',
    'reports.scheduled': 'Scheduled Reports',
    'reports.history': 'Report History',
    
    // AI Solution
    'ai.title': 'AI Solution',
    'ai.subtitle': 'AI Assistant for advanced financial analysis',
    'ai.assistant': 'Tralis AI Assistant',
    'ai.analysis': 'Automated analysis and intelligent commands for your business',
    'ai.ask': 'Ask your AI assistant',
    'ai.send': 'Send',
    'ai.suggestions': 'Suggestions',
    'ai.insights': 'AI Insights',
    'ai.chat': 'AI Chat',
    'ai.scenario-analysis': 'Scenario Analysis',
    'ai.financial-modeling': 'Financial Modeling',
    'ai.predictive-analytics': 'Predictive Analytics',
    'ai.recommendations': 'Recommendations',
    'ai.automated-reports': 'Automated Reports',
    'ai.intelligent-alerts': 'Intelligent Alerts',
    'ai.conversation-history': 'Conversation History',
    'ai.save-analysis': 'Save Analysis',
    
    // Lending
    'lending.title': 'Lending Solutions',
    'lending.subtitle': 'Find the best financing options for your business',
    'lending.options': 'Available Options',
    'lending.apply': 'Apply for Financing',
    'lending.calculator': 'Loan Calculator',
    'lending.eligibility': 'Check Eligibility',
    'lending.loan-types': 'Loan Types',
    'lending.business-loan': 'Business Loan',
    'lending.line-of-credit': 'Line of Credit',
    'lending.equipment-financing': 'Equipment Financing',
    'lending.invoice-factoring': 'Invoice Factoring',
    'lending.requirements': 'Requirements',
    'lending.documentation': 'Documentation',
    'lending.application-status': 'Application Status',
    'lending.interest-rates': 'Interest Rates',
    'lending.terms': 'Terms',
    'lending.pre-approval': 'Pre-approval',
    
    // Calendar
    'calendar.title': 'Financial Calendar',
    'calendar.subtitle': 'Manage important deadlines and appointments',
    'calendar.events': 'Events',
    'calendar.deadlines': 'Deadlines',
    'calendar.meetings': 'Meetings',
    'calendar.add': 'Add Event',
    'calendar.today': 'Today',
    'calendar.week': 'Week',
    'calendar.month': 'Month',
    'calendar.year': 'Year',
    'calendar.upcoming': 'Upcoming Events',
    'calendar.overdue': 'Overdue',
    'calendar.reminders': 'Reminders',
    'calendar.notifications': 'Notifications',
    'calendar.recurring': 'Recurring',
    'calendar.sync': 'Sync',
    'calendar.export': 'Export',
    'calendar.import': 'Import',
    
    // Packages
    'packages.title': 'Packages & Plans',
    'packages.subtitle': 'Choose the perfect plan for your needs',
    'packages.current': 'Current Plan',
    'packages.upgrade': 'Upgrade',
    'packages.features': 'Features',
    'packages.contact': 'Contact Team',
    'packages.free': 'Free',
    'packages.basic': 'Basic',
    'packages.professional': 'Professional',
    'packages.enterprise': 'Enterprise',
    'packages.monthly': 'Monthly',
    'packages.yearly': 'Yearly',
    'packages.save': 'Save',
    'packages.most-popular': 'Most Popular',
    'packages.unlimited': 'Unlimited',
    'packages.support': 'Support',
    'packages.billing': 'Billing',
    'packages.cancel-anytime': 'Cancel anytime',
    
    // Data Import
    'import.title': 'Data Import',
    'import.subtitle': 'Upload your financial data',
    'import.upload': 'Upload File',
    'import.excel': 'Excel File',
    'import.csv': 'CSV File',
    'import.template': 'Download Template',
    'import.process': 'Process',
    'import.supported-formats': 'Supported Formats',
    'import.drag-drop': 'Drag and drop files here',
    'import.or': 'or',
    'import.browse': 'Browse Files',
    'import.max-size': 'Max size',
    'import.preview': 'Preview',
    'import.mapping': 'Field Mapping',
    'import.validation': 'Validation',
    'import.import-progress': 'Import Progress',
    'import.success': 'Import completed successfully',
    'import.error': 'Error during import',
    'import.history': 'Import History',
    
    // User Profile
    'profile.title': 'User Profile',
    'profile.personal': 'Personal Information',
    'profile.company': 'Company Information',
    'profile.security': 'Security',
    'profile.save': 'Save Changes',
    'profile.edit': 'Edit',
    'profile.change-password': 'Change Password',
    'profile.current-password': 'Current Password',
    'profile.new-password': 'New Password',
    'profile.confirm-password': 'Confirm Password',
    'profile.two-factor': 'Two-Factor Authentication',
    'profile.notifications': 'Notifications',
    'profile.preferences': 'Preferences',
    'profile.timezone': 'Timezone',
    'profile.language': 'Language',
    'profile.currency': 'Currency',
    'profile.delete-account': 'Delete Account',
    
    // Homepage Hero
    'hero.badge': 'Global Innovation',
    'hero.title': 'Unlock Your Startup\'s',
    'hero.title.highlight': 'Financial',
    'hero.title.end': 'Potential',
    'hero.subtitle': 'We empower startups and SMEs to compete with larger companies through cutting-edge financial analytics and AI-powered insights. Transform your financial management and unlock your business potential.',
    'hero.cta.primary': 'Start Free Trial',
    'hero.cta.secondary': 'Login to Your Account',
    
    // Video Section
    'video.title': 'Discover Tralis AI in Action',
    'video.subtitle': 'Watch how Tralis AI transforms your company\'s financial management with a complete platform tour.',
    'video.tutorial.title': 'Complete Tralis AI Tutorial',
    'video.tutorial.duration': 'Duration: 8 minutes',
    'video.tutorial.cta': 'Watch Video',
    'video.card1.title': 'Financial Dashboard',
    'video.card1.desc': 'View KPIs and real-time metrics',
    'video.card2.title': 'AI Analytics',
    'video.card2.desc': 'Predictive insights and recommendations',
    'video.card3.title': 'Advanced Reports',
    'video.card3.desc': 'Investor-ready documents',
    
    // Features
    'features.title': 'Everything You Need to Master Your Finances',
    'features.subtitle': 'Our comprehensive platform provides all the tools and insights needed to make informed financial decisions and drive growth.',
    'features.dashboard.title': 'Real-Time Dashboard',
    'features.dashboard.desc': 'Monitor your company\'s financial health with intuitive visualizations and key performance indicators.',
    'features.ai.title': 'AI-Powered Insights',
    'features.ai.desc': 'Get personalized recommendations and predictive analytics tailored to your business.',
    'features.security.title': 'Secure & Compliant',
    'features.security.desc': 'Enterprise-level security with full compliance to international regulations.',
    'features.funding.title': 'Funding Preparation',
    'features.funding.desc': 'Get ready for investments with comprehensive financial reports and projections.',
    
    // Testimonials
    'testimonials.title': 'Chosen by Growing Companies',
    'testimonials.quote1': 'Tralis AI has revolutionized how we manage our finances. The AI insights are incredibly accurate.',
    'testimonials.quote2': 'Finally, a financial platform built specifically for startups. The dashboards are amazing!',
    
    // CTA Section
    'cta.title': 'Ready to Transform Your Financial Management?',
    'cta.subtitle': 'Join hundreds of startups already using Tralis AI to drive growth and make better decisions.',
    'cta.button': 'Start Today',
    
    // Why Tralis AI Section
    'why.title': 'Why Choose Tralis AI?',
    'why.subtitle': 'The most advanced financial intelligence platform for startups and SMEs',
    'why.ai-powered': 'AI-Powered',
    'why.ai-powered.desc': 'Advanced machine learning algorithms for predictive analysis and automated insights',
    'why.real-time': 'Real-Time Data',
    'why.real-time.desc': 'Monitor your company performance with instant updates and live dashboards',
    'why.compliance': 'Full Compliance',
    'why.compliance.desc': 'Meet all international regulations with automated reports and audit trails',
    'why.scalable': 'Scalable',
    'why.scalable.desc': 'Grows with your business, from startup to enterprise, with modular features',
    'why.support': '24/7 Support',
    'why.support.desc': 'Expert team available anytime to support your financial growth',
    'why.integration': 'Easy Integration',
    'why.integration.desc': 'Connect all your existing systems with modern and secure APIs',
    
    // Language Selection
    'language.select': 'Select Language',
    'language.italian': 'Italiano',
    'language.english': 'English',
    'language.spanish': 'Español',
    
    // Common
    'common.loading': 'Loading...',
    'common.error': 'Error',
    'common.success': 'Success',
    'common.cancel': 'Cancel',
    'common.confirm': 'Confirm',
    'common.delete': 'Delete',
    'common.edit': 'Edit',
    'common.save': 'Save',
    'common.back': 'Back',
    'common.next': 'Next',
    'common.previous': 'Previous',
    'common.close': 'Close',
    'common.search': 'Search',
    'common.filter': 'Filter',
    'common.sort': 'Sort',
    'common.refresh': 'Refresh',
    'common.settings': 'Settings',
    'common.help': 'Help',
    'common.documentation': 'Documentation',
    'common.contact': 'Contact',
    'common.support': 'Support',
  },
  es: {
    // Navigation
    'nav.product': 'PRODUCTO',
    'nav.solutions': 'SOLUCIONES',
    'nav.why': '¿POR QUÉ TRALIS AI?',
    'nav.resources': 'RECURSOS',
    'nav.pricing': 'PRECIOS',
    'nav.login': 'Iniciar Sesión',
    'nav.signup': 'Registro Gratis',
    'nav.contact': 'Contáctanos',
    'nav.glossary': 'Glosario',
    
    // Sidebar
    'sidebar.dashboard': 'Dashboard',
    'sidebar.analytics': 'Analytics',
    'sidebar.reports': 'Reportes',
    'sidebar.data-import': 'Importar Datos',
    'sidebar.ai-solution': 'Solución AI',
    'sidebar.lending': 'Financiamiento',
    'sidebar.calendar': 'Calendario',
    'sidebar.packages': 'Paquetes',
    
    // Header
    'header.profile': 'Perfil',
    'header.settings': 'Configuración',
    'header.logout': 'Cerrar Sesión',
    'header.plan': 'Plan',
    
    // Auth Modal
    'auth.welcome': 'Bienvenido de Vuelta',
    'auth.credentials': 'Ingresa tus credenciales para acceder a tu dashboard de Tralis AI',
    'auth.create': 'Crear Cuenta',
    'auth.join': 'Únete a Tralis AI y desbloquea tu potencial financiero',
    'auth.email': 'Email',
    'auth.password': 'Contraseña',
    'auth.firstName': 'Nombre',
    'auth.lastName': 'Apellido',
    'auth.company': 'Empresa',
    'auth.login': 'Iniciar Sesión',
    'auth.signup': 'Crear Cuenta',
    'auth.logging': 'Iniciando sesión...',
    'auth.creating': 'Creando cuenta...',
    'auth.terms': 'Al continuar, aceptas los Términos de Servicio y Política de Privacidad de Tralis AI',
    
    // Dashboard
    'dashboard.title': 'Dashboard Financiero',
    'dashboard.subtitle': 'Resumen completo de tu rendimiento financiero',
    'dashboard.welcome': 'Bienvenido a tu dashboard financiero',
    'dashboard.overview': 'Resumen',
    'dashboard.revenue': 'Ingresos',
    'dashboard.expenses': 'Gastos',
    'dashboard.profit': 'Ganancia',
    'dashboard.cashflow': 'Flujo de Efectivo',
    'dashboard.month': 'Este Mes',
    'dashboard.growth': 'Crecimiento',
    'dashboard.vs-last': 'vs mes pasado',
    'dashboard.financial-summary': 'Resumen Financiero',
    'dashboard.recent-transactions': 'Transacciones Recientes',
    'dashboard.view-all': 'Ver Todo',
    'dashboard.cash-flow-trend': 'Tendencia del Flujo de Efectivo',
    'dashboard.revenue-breakdown': 'Desglose de Ingresos',
    'dashboard.alerts': 'Alertas',
    'dashboard.no-alerts': 'No hay alertas en este momento',
    'dashboard.quick-actions': 'Acciones Rápidas',
    'dashboard.generate-report': 'Generar Reporte',
    'dashboard.schedule-meeting': 'Programar Reunión',
    'dashboard.ai-insights': 'Insights AI',
    
    // Analytics
    'analytics.title': 'Analytics Avanzados',
    'analytics.subtitle': 'Análisis profundos de tu rendimiento financiero',
    'analytics.revenue-trend': 'Tendencia de Ingresos',
    'analytics.expense-breakdown': 'Desglose de Gastos',
    'analytics.profit-margin': 'Margen de Ganancia',
    'analytics.kpi': 'Indicadores Clave',
    'analytics.forecast': 'Pronóstico',
    'analytics.insights': 'Insights',
    'analytics.performance': 'Rendimiento',
    'analytics.comparison': 'Comparación',
    'analytics.financial-ratios': 'Ratios Financieros',
    'analytics.liquidity': 'Liquidez',
    'analytics.profitability': 'Rentabilidad',
    'analytics.efficiency': 'Eficiencia',
    'analytics.leverage': 'Apalancamiento',
    'analytics.market-analysis': 'Análisis de Mercado',
    'analytics.competitive-analysis': 'Análisis Competitivo',
    'analytics.scenario-analysis': 'Análisis de Escenarios',
    'analytics.risk-assessment': 'Evaluación de Riesgos',
    
    // Reports
    'reports.title': 'Reportes Financieros',
    'reports.subtitle': 'Genera y visualiza reportes detallados',
    'reports.monthly': 'Reporte Mensual',
    'reports.quarterly': 'Reporte Trimestral',
    'reports.annual': 'Reporte Anual',
    'reports.custom': 'Reporte Personalizado',
    'reports.generate': 'Generar Reporte',
    'reports.download': 'Descargar',
    'reports.export': 'Exportar',
    'reports.financial-statements': 'Estados Financieros',
    'reports.cash-flow-statement': 'Estado de Flujo de Efectivo',
    'reports.income-statement': 'Estado de Resultados',
    'reports.balance-sheet': 'Balance General',
    'reports.investor-reports': 'Reportes para Inversores',
    'reports.executive-summary': 'Resumen Ejecutivo',
    'reports.detailed-analysis': 'Análisis Detallado',
    'reports.templates': 'Plantillas',
    'reports.scheduled': 'Reportes Programados',
    'reports.history': 'Historial de Reportes',
    
    // AI Solution
    'ai.title': 'Solución AI',
    'ai.subtitle': 'Asistente AI para análisis financiero avanzado',
    'ai.assistant': 'Asistente Tralis AI',
    'ai.analysis': 'Análisis automático y comandos inteligentes para tu negocio',
    'ai.ask': 'Pregunta a tu asistente AI',
    'ai.send': 'Enviar',
    'ai.suggestions': 'Sugerencias',
    'ai.insights': 'Insights AI',
    'ai.chat': 'Chat AI',
    'ai.scenario-analysis': 'Análisis de Escenarios',
    'ai.financial-modeling': 'Modelado Financiero',
    'ai.predictive-analytics': 'Analytics Predictivos',
    'ai.recommendations': 'Recomendaciones',
    'ai.automated-reports': 'Reportes Automatizados',
    'ai.intelligent-alerts': 'Alertas Inteligentes',
    'ai.conversation-history': 'Historial de Conversaciones',
    'ai.save-analysis': 'Guardar Análisis',
    
    // Lending
    'lending.title': 'Soluciones de Financiamiento',
    'lending.subtitle': 'Encuentra las mejores opciones de financiamiento para tu negocio',
    'lending.options': 'Opciones Disponibles',
    'lending.apply': 'Solicitar Financiamiento',
    'lending.calculator': 'Calculadora de Préstamos',
    'lending.eligibility': 'Verificar Elegibilidad',
    'lending.loan-types': 'Tipos de Préstamos',
    'lending.business-loan': 'Préstamo Comercial',
    'lending.line-of-credit': 'Línea de Crédito',
    'lending.equipment-financing': 'Financiamiento de Equipos',
    'lending.invoice-factoring': 'Factoring de Facturas',
    'lending.requirements': 'Requisitos',
    'lending.documentation': 'Documentación',
    'lending.application-status': 'Estado de Solicitud',
    'lending.interest-rates': 'Tasas de Interés',
    'lending.terms': 'Términos',
    'lending.pre-approval': 'Pre-aprobación',
    
    // Calendar
    'calendar.title': 'Calendario Financiero',
    'calendar.subtitle': 'Gestiona fechas límite y citas importantes',
    'calendar.events': 'Eventos',
    'calendar.deadlines': 'Fechas Límite',
    'calendar.meetings': 'Reuniones',
    'calendar.add': 'Agregar Evento',
    'calendar.today': 'Hoy',
    'calendar.week': 'Semana',
    'calendar.month': 'Mes',
    'calendar.year': 'Año',
    'calendar.upcoming': 'Próximos Eventos',
    'calendar.overdue': 'Vencidos',
    'calendar.reminders': 'Recordatorios',
    'calendar.notifications': 'Notificaciones',
    'calendar.recurring': 'Recurrentes',
    'calendar.sync': 'Sincronizar',
    'calendar.export': 'Exportar',
    'calendar.import': 'Importar',
    
    // Packages
    'packages.title': 'Paquetes y Planes',
    'packages.subtitle': 'Elige el plan perfecto para tus necesidades',
    'packages.current': 'Plan Actual',
    'packages.upgrade': 'Actualizar',
    'packages.features': 'Características',
    'packages.contact': 'Contactar Equipo',
    'packages.free': 'Gratis',
    'packages.basic': 'Básico',
    'packages.professional': 'Profesional',
    'packages.enterprise': 'Empresarial',
    'packages.monthly': 'Mensual',
    'packages.yearly': 'Anual',
    'packages.save': 'Ahorrar',
    'packages.most-popular': 'Más Popular',
    'packages.unlimited': 'Ilimitado',
    'packages.support': 'Soporte',
    'packages.billing': 'Facturación',
    'packages.cancel-anytime': 'Cancelar en cualquier momento',
    
    // Data Import
    'import.title': 'Importar Datos',
    'import.subtitle': 'Sube tus datos financieros',
    'import.upload': 'Subir Archivo',
    'import.excel': 'Archivo Excel',
    'import.csv': 'Archivo CSV',
    'import.template': 'Descargar Plantilla',
    'import.process': 'Procesar',
    'import.supported-formats': 'Formatos Soportados',
    'import.drag-drop': 'Arrastra y suelta archivos aquí',
    'import.or': 'o',
    'import.browse': 'Explorar Archivos',
    'import.max-size': 'Tamaño máximo',
    'import.preview': 'Vista Previa',
    'import.mapping': 'Mapeo de Campos',
    'import.validation': 'Validación',
    'import.import-progress': 'Progreso de Importación',
    'import.success': 'Importación completada exitosamente',
    'import.error': 'Error durante la importación',
    'import.history': 'Historial de Importaciones',
    
    // User Profile
    'profile.title': 'Perfil de Usuario',
    'profile.personal': 'Información Personal',
    'profile.company': 'Información de Empresa',
    'profile.security': 'Seguridad',
    'profile.save': 'Guardar Cambios',
    'profile.edit': 'Editar',
    'profile.change-password': 'Cambiar Contraseña',
    'profile.current-password': 'Contraseña Actual',
    'profile.new-password': 'Nueva Contraseña',
    'profile.confirm-password': 'Confirmar Contraseña',
    'profile.two-factor': 'Autenticación de Dos Factores',
    'profile.notifications': 'Notificaciones',
    'profile.preferences': 'Preferencias',
    'profile.timezone': 'Zona Horaria',
    'profile.language': 'Idioma',
    'profile.currency': 'Moneda',
    'profile.delete-account': 'Eliminar Cuenta',
    
    // Homepage Hero
    'hero.badge': 'Innovación Global',
    'hero.title': 'Desbloquea el Potencial',
    'hero.title.highlight': 'Financiero',
    'hero.title.end': 'de tu Startup',
    'hero.subtitle': 'Empoderamos a startups y PyMEs para competir con empresas más grandes a través de análisis financieros de vanguardia e insights impulsados por IA. Transforma tu gestión financiera y desbloquea el potencial de tu negocio.',
    'hero.cta.primary': 'Iniciar Prueba Gratuita',
    'hero.cta.secondary': 'Acceder a tu Cuenta',
    
    // Video Section
    'video.title': 'Descubre Tralis AI en Acción',
    'video.subtitle': 'Mira cómo Tralis AI transforma la gestión financiera de tu empresa con un tour completo de la plataforma.',
    'video.tutorial.title': 'Tutorial Completo de Tralis AI',
    'video.tutorial.duration': 'Duración: 8 minutos',
    'video.tutorial.cta': 'Ver Video',
    'video.card1.title': 'Panel Financiero',
    'video.card1.desc': 'Visualiza KPIs y métricas en tiempo real',
    'video.card2.title': 'Análisis con IA',
    'video.card2.desc': 'Insights predictivos y recomendaciones',
    'video.card3.title': 'Reportes Avanzados',
    'video.card3.desc': 'Documentos listos para inversores',
    
    // Features
    'features.title': 'Todo lo que Necesitas para Dominar tus Finanzas',
    'features.subtitle': 'Nuestra plataforma integral proporciona todas las herramientas e insights necesarios para tomar decisiones financieras informadas e impulsar el crecimiento.',
    'features.dashboard.title': 'Dashboard en Tiempo Real',
    'features.dashboard.desc': 'Monitorea la salud financiera de tu empresa con visualizaciones intuitivas e indicadores clave de rendimiento.',
    'features.ai.title': 'Insights Impulsados por IA',
    'features.ai.desc': 'Obtén recomendaciones personalizadas y análisis predictivos adaptados a tu negocio.',
    'features.security.title': 'Seguro y Conforme',
    'features.security.desc': 'Seguridad de nivel empresarial con pleno cumplimiento de regulaciones internacionales.',
    'features.funding.title': 'Preparación de Financiamiento',
    'features.funding.desc': 'Prepárate para inversiones con reportes financieros integrales y proyecciones.',
    
    // Testimonials
    'testimonials.title': 'Elegido por Empresas en Crecimiento',
    'testimonials.quote1': 'Tralis AI ha revolucionado la forma en que gestionamos nuestras finanzas. Los insights de IA son increíblemente precisos.',
    'testimonials.quote2': '¡Finalmente, una plataforma financiera construida específicamente para startups. Los dashboards son increíbles!',
    
    // CTA Section  
    'cta.title': '¿Listo para Transformar tu Gestión Financiera?',
    'cta.subtitle': 'Únete a cientos de startups que ya usan Tralis AI para impulsar el crecimiento y tomar mejores decisiones.',
    'cta.button': 'Comenzar Hoy',
    
    // Why Tralis AI Section
    'why.title': '¿Por Qué Elegir Tralis AI?',
    'why.subtitle': 'La plataforma de inteligencia financiera más avanzada para startups y PyMEs',
    'why.ai-powered': 'Impulsado por IA',
    'why.ai-powered.desc': 'Algoritmos avanzados de machine learning para análisis predictivo e insights automatizados',
    'why.real-time': 'Datos en Tiempo Real',
    'why.real-time.desc': 'Monitorea el rendimiento de tu empresa con actualizaciones instantáneas y dashboards en vivo',
    'why.compliance': 'Cumplimiento Total',
    'why.compliance.desc': 'Cumple con todas las regulaciones internacionales con reportes automatizados y rastros de auditoría',
    'why.scalable': 'Escalable',
    'why.scalable.desc': 'Crece con tu negocio, desde startup hasta empresa, con características modulares',
    'why.support': 'Soporte 24/7',
    'why.support.desc': 'Equipo experto disponible en cualquier momento para apoyar tu crecimiento financiero',
    'why.integration': 'Integración Fácil',
    'why.integration.desc': 'Conecta todos tus sistemas existentes con APIs modernas y seguras',
    
    // Language Selection
    'language.select': 'Seleccionar Idioma',
    'language.italian': 'Italiano',
    'language.english': 'Inglés',
    'language.spanish': 'Español',
    
    // Common
    'common.loading': 'Cargando...',
    'common.error': 'Error',
    'common.success': 'Éxito',
    'common.cancel': 'Cancelar',
    'common.confirm': 'Confirmar',
    'common.delete': 'Eliminar',
    'common.edit': 'Editar',
    'common.save': 'Guardar',
    'common.back': 'Atrás',
    'common.next': 'Siguiente',
    'common.previous': 'Anterior',
    'common.close': 'Cerrar',
    'common.search': 'Buscar',
    'common.filter': 'Filtrar',
    'common.sort': 'Ordenar',
    'common.refresh': 'Actualizar',
    'common.settings': 'Configuración',
    'common.help': 'Ayuda',
    'common.documentation': 'Documentación',
    'common.contact': 'Contacto',
    'common.support': 'Soporte',
  }
};
